### ISSUE TITLE
Class Mail does not exist

### ISSUE THREAD

**Issue by themall7** [Eden-PHP/Mail#38]
When I tried to get maillist from gmail it returns followings. Where Can I get Mail Class?
Fatal error:  Uncaught exception 'Eden\Core\Exception' with message 'Class Mail does not exist' in /home/user/www/vendor/eden/core/src/Control.php:26
Stack trace:
#0 /home/user/www/vendor/eden/core/src/Base.php(246): Eden\Core\Exception::i('Class Mail does...')
#1 /home/user/www/vendor/eden/core/src/Control.php(26): Eden\Core\Base->__invoke(Array)
#2 /home/user/www/classes/MailReader.php(65): eden('mail')
#3 /home/user/www/classes/MailReader.php(112): MailReader->read_email()
#4 /home/user/www/scripts/mail-parser.php(24): MailReader->process()
#5 {main}
  thrown in /home/user/www/vendor/eden/core/src/Control.php on line 26

**Comment by cblanquera** [comment]
try
```
use Eden\Mail\Index as Mail;
$mail = new Mail();
$mail->imap('imap.gmail.com', 
	'your_email@gmail.com', 
	'[YOUR PASSWORD]', 
	993, 
	true);
//or any other factory methods from there.
```
https://github.com/Eden-PHP/Mail/blob/master/src/Index.php

**Comment by amdxypf** [comment]
I encountered the same problem
my code：
```
<?php
	require "autoload.php";
	Eden::DECORATOR;

	eden()->inspect('Hello World');


	use Eden\Mail\Index as Mail;

	$imap = eden('mail')->imap(
		'imap.***.com',
		'*****@**.com',
		'*******',
		993,
		true);
	$mailboxes = $imap->getMailboxes();
	var_dump($mailboxes);
```
it show：
```
<pre>INSPECTING Variable:</pre><pre>Hello World</pre>
Fatal error: Uncaught exception 'Eden\Core\Exception' with message 'Class Mail does not exist' in D:\documents\code\gitlab\testaaa\vendor\eden\core\src\Control.php:26
Stack trace:
#0 D:\documents\code\gitlab\testaaa\vendor\eden\core\src\Base.php(246): Eden\Core\Exception::i('Class Mail does...')
#1 D:\documents\code\gitlab\testaaa\vendor\eden\core\src\Control.php(26): Eden\Core\Base->__invoke(Array)
#2 D:\documents\code\gitlab\testaaa\vendor\test.php(10): eden('mail')
#3 {main}
  thrown in D:\documents\code\gitlab\testaaa\vendor\eden\core\src\Control.php on line 26
```
How should I do ?

**Comment by thefunkyjoint** [comment]
Is this library dead ? Does it work ?
